APIDevTools/swagger-parser

- lib/resolve.js
Property could have '$ref' name it's valid name.
Moreover such swagger files exist in the wild see [swagger] (https://github.com/APIs-guru/api-models/blob/master/google/discovery/v1/swagger.json#L225) for Google Discovery service.
It would be common problem for any API which return json-schema.
I implement workaround it solve problem but in the same time allowing incorrect references.
I understand that for proper reference detection you need to re-implement half of your library.
In any case it should be addressed in FAQ
> Workaround for '$ref' property name.

- lib/read.js
Fixes #10
Could be worth considering the popular [request](https://www.npmjs.com/package/request) module which supports with a simple DSL syntax.
> Added support for downloading remote files over https

- README.md
- tests/specs/real-world/real-world.spec.js
Hi @BigstickCarpet,
We are migrating our URLs to `APIs.guru` domain, here is more details:
https://github.com/APIs-guru/api-models/issues/85
Plus I add `Tested on APIs.guru` badge, hope you will like it :smile: 
[![Tested on APIs.guru](https://api.apis.guru/badges/tested_on.svg)](https://APIs.guru)
> [Do not merge] Migrate APIs.guru related URLs 

- lib/validate-schema.js
I ran into an issue with swagger-parser using node v7.5.0 and Typescript 2.1.6 where `swagger-schema-official/schema` couldn't be required. Adding `.json` to the require statement fixes the problem.
> Fix swagger-schema-official JSON import

- lib/validate-schema.js
`require('swagger-schema-official/schema')` doesn't resolve when using webpack. By changing to `require('swagger-schema-official/schema.json')`, the spec resolves.
> Changes schema path to schema.json

- lib/validate-spec.js
https://github.com/BigstickCarpet/swagger-parser/issues/73
This issue accounts for instances where there are extensions in the responses object and those extensions can be null.
> Issue 73: ensure responses is populated with an object

- lib/validators/spec.js
- test/specs/validate-spec/valid/file-vendor-specific-consumes-formdata.yaml
- test/specs/validate-spec/valid/file-vendor-specific-consumes-urlencoded.yaml
- test/specs/validate-spec/validate-spec.spec.js
Replaced the hard coded media type strings with regexes that allow for
vendor specific versions of the types to make things a bit more
flexible.
> Accept vendor specific versions of consumes types for file params

- lib/validators/spec.js
- test/specs/validate-spec/invalid/duplicate-operation-ids.yaml
- test/specs/validate-spec/validate-spec.spec.js
> Add check for duplicate operation ids

- lib/index.js
OAS 3.0.2 is a patch release, there's no changes of the behavior of the spec. 😉 
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.2
> Add support for OAS 3.0.2

- lib/index.d.ts
This resolves https://github.com/APIDevTools/swagger-parser/issues/119
> validate field in type definition of options

- lib/index.js
Add support for version 3.0.3
Version was released about 3 weeks ago: https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.3
> Support openapi version 3.0.3

- test/specs/real-world/known-errors.js
Running `npm run node:test` failed because some API's fail to pass validation.
This PR assumes that these are all bugs in specifications and not in swagger-parser.
It should make CI on swagger-parser succeed again so we can continue its development.
(esp. adding support for v3.1 ;-))
Kind regards,
Hans
> Updated known-errors to make CI work again

- test/specs/real-world/fetch-api-list.js
- test/specs/real-world/known-errors.js
I've skipped 3.1.0 yamls which is going to be supported only after https://github.com/APIDevTools/swagger-parser/pull/171
Then I added what I can see are errors with the api to known errors list.
fwiw the spec is also failing on v10.0.2 presumably because the swagger yaml's has changed since last tag (assuming that the build was green when last tag was made) but I'm just trying to get main green asap so that it can get another tag release... so that I can get the z-schema cve fix....
> Skip known errors or unsupported api in real-world api spec

- package-lock.json
- package.json
- test/specs/real-world/known-errors.js
Trying to get this releases as there are laods of recent improvements, including OAS 3.1 support, but I am getting a few problems. 
I've had to remove `npm run update` from release because of various dependency hell problems around libsass, npm-check and uuid being triggered by audit fix. We can solve that later. 
With that removed I'm seeing the following test fail: 
```
API with circular (recursive) $refs
✔ should parse successfully
✔ should resolve successfully
✔ should dereference successfully
1) should validate successfully
23 passing (258ms)
1 failing
1) API with circular (recursive) $refs
should validate successfully:
Error: Error resolving $ref pointer "/Users/phil/src/swagger-parser/test/specs/circular/person.yaml".
"/Users/phil/src/swagger-parser/test/specs/circular/person.yaml" …
```
> Trying to release 

- test/specs/real-world/known-errors.js
Ignoring this API should get all unit tests passing again so we can finally get a release out for 3.1 support.
> fix: ignoring a busted API that's breaking unit tests

- package.json
A dependency used in this project @apidevtools/json-schema-ref-parser is vulnerable to a prototype pollution attack, as listed in https://nvd.nist.gov/vuln/detail/CVE-2024-29651 - https://github.com/advisories/GHSA-5f97-h2c2-826q
This PR bumps the dependency to prevent any vulnerabilities.
Closes https://github.com/APIDevTools/swagger-parser/issues/255
References
https://ossindex.sonatype.org/vulnerability/CVE-2024-29651
https://github.com/advisories/GHSA-5f97-h2c2-826q
https://github.com/APIDevTools/json-schema-ref-parser/commit/8cad7f72c15b198f4d0b5b1c8a3a979b2e4baa82
https://nvd.nist.gov/vuln/detail/CVE-2024-29651
> chore(dependencies): bump @apidevtools/json-schema-ref-parser to 11.6.2

- lib/index.js
fixes https://github.com/microsoft/kiota/issues/5944
OAS 3.1.1 and 3.0.4 were [released as maintenance releases](https://www.openapis.org/blog/2024/10/25/announcing-openapi-specification-patch-releases) and don't change anything from a functional perspective.
We're starting to see those new versions show up in OAS documents, and this library is failing to parse them simply based on the version number.
- adds 3.0.4 to the list of supported versions.
- adds 3.1.1 to the list of supported versions.
- moves the version arrays to constants to avoid allocating an array on each call.
> fix: adds missing version 3.0.4 and 3.1.1

- README.md
- SECURITY.md
Added security guidance on how to use the library safely to prevent local file inclusion and potential sensitive information disclosure.
> Added security guidance

- lib/index.js
Old PR: https://github.com/APIDevTools/swagger-parser/pull/175
fixes https://github.com/APIDevTools/swagger-parser/issues/116
> More error details fixes #116

- lib/validators/schema.js
Users of this package keep running into the following import issue: This forces users to include `ajv-draft-04` into their project dependencies even if they are not directly using it. This PR proposes moving the import statement into the only code block where it is actually required and thus (hopefully) avoiding the error. Its a bit surprising that the dependencies don't force the package to be there. Maybe there is some other problem at play...
```
node:internal/modules/cjs/loader:1248
const err = new Error(message);
^
Error: Cannot find module 'ajv/dist/core'
Require stack:
- home/project/node_modules/ajv-draft-04/dist/index.js
- home/project/node_modules/@apidevtools/swagger-parser/lib/validators/schema.js
- home/project/node_modules/@apidevtools/swagger-parser/lib/index.js
at …
```
> Fix Import Error: ajv-draft-04
